# Generated by Django 6.0 on 2026-02-23 11:07

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('body_text', models.TextField(blank=True, null=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('template_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('error', models.TextField(default=False)),
                ('region', models.CharField(choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], default='BD', max_length=2)),
                ('service', models.CharField(choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10)),
                ('request_by', models.CharField(max_length=255)),
                ('api_path', models.CharField(max_length=255)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_type', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('NOTIFICATION', 'Notification')], default='EMAIL', max_length=15)),
                ('credentials', models.JSONField(blank=True, null=True)),
                ('region', models.CharField(choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], default='BD', max_length=2)),
                ('service', models.CharField(choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_QUEUE', 'In Queue'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('template_type', models.CharField(blank=True, choices=[('MESSAGE', 'Message'), ('EMAIL', 'Email')], max_length=10, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(blank=True, max_length=10, null=True)),
                ('to_contact', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255))),
                ('region', models.CharField(choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], default='BD', max_length=2)),
                ('service', models.CharField(choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.provider')),
            ],
        ),
    ]
