# Generated by Django 6.0 on 2026-03-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='api_path',
            field=models.URLField(max_length=255),
        ),
    ]
