# Generated by Django 6.0 on 2026-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_logs_api_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='service',
            field=models.CharField(choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='logs',
            name='service',
            field=models.CharField(choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='service',
            field=models.CharField(choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], default='GOZAYAAN', max_length=10),
        ),
    ]
