# Generated by Django 6.0 on 2026-03-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_service_alter_logs_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='code',
            field=models.CharField(blank=True, choices=[('google_smtp', 'Google SMTP'), ('sendgrid', 'SendGrid'), ('aws_ses', 'AWS SES'), ('mailgun', 'Mailgun')], max_length=50, null=True),
        ),
    ]
