# Generated by Django 6.0 on 2026-02-23 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('subject', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254, verbose_name='From')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('INSTANT', 'Instant')], default='LOW', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retry', models.IntegerField(default=5)),
                ('region', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], max_length=2, null=True)),
                ('service', models.CharField(blank=True, choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='email_attachments', to='events.content')),
                ('bcc_contacts', models.ManyToManyField(blank=True, related_name='email_bcc_templates', to='audience.contact')),
                ('bcc_group', models.ManyToManyField(blank=True, related_name='email_bcc_groups', to='audience.group')),
                ('cc_contacts', models.ManyToManyField(blank=True, related_name='email_cc_templates', to='audience.contact')),
                ('cc_group', models.ManyToManyField(blank=True, related_name='email_cc_groups', to='audience.group')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='events.content')),
                ('to_contacts', models.ManyToManyField(blank=True, related_name='email_to_contacts', to='audience.contact')),
                ('to_group', models.ManyToManyField(blank=True, related_name='email_to_groups', to='audience.group')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('template_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message_type', models.CharField(choices=[('SMS', 'SMS'), ('NOTIFICATION', 'Notification')], default='SMS', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('HIGH', 'High'), ('INSTANT', 'Instant')], default='LOW', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('max_retry', models.IntegerField(default=5)),
                ('region', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], max_length=2, null=True)),
                ('service', models.CharField(blank=True, choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='message_contacts', to='audience.contact')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='events.content')),
                ('groups', models.ManyToManyField(blank=True, related_name='message_groups', to='audience.group')),
            ],
        ),
    ]
