# Generated by Django 6.0 on 2026-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_groups', models.JSONField(default=list)),
                ('region', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], max_length=2, null=True)),
                ('service', models.CharField(blank=True, choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], max_length=10, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='service',
            field=models.CharField(blank=True, choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='service',
            field=models.CharField(blank=True, choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True),
        ),
    ]
