# Generated by Django 6.0 on 2026-02-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=25, null=True)),
                ('last_name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], max_length=2, null=True)),
                ('service', models.CharField(blank=True, choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(blank=True, choices=[('BD', 'Bangladesh'), ('PK', 'Pakistan'), ('SG', 'Singapore'), ('MY', 'Malaysia')], max_length=2, null=True)),
                ('service', models.CharField(blank=True, choices=[('GOZAYAAN', 'GoZyaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contact_groups', to='audience.contact')),
            ],
        ),
    ]
