# Generated by Django 6.0 on 2026-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='service',
            field=models.CharField(blank=True, choices=[('GOZAYAAN', 'Gozayaan'), ('HOMETOWN', 'Hometown')], max_length=20, null=True),
        ),
    ]
